// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/QiSliderVue2/button.vue')['default'];
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElAvatar: typeof import('element-plus/es')['ElAvatar'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElDivider: typeof import('element-plus/es')['ElDivider'];
    ElDrawer: typeof import('element-plus/es')['ElDrawer'];
    ElDropdown: typeof import('element-plus/es')['ElDropdown'];
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
    ElFooter: typeof import('element-plus/es')['ElFooter'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElPagination: typeof import('element-plus/es')['ElPagination'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    ElSwitch: typeof import('element-plus/es')['ElSwitch'];
    ElTable: typeof import('element-plus/es')['ElTable'];
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
    ElTabPane: typeof import('element-plus/es')['ElTabPane'];
    ElTabs: typeof import('element-plus/es')['ElTabs'];
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker'];
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    ElTree: typeof import('element-plus/es')['ElTree'];
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default'];
    IEpCirclePlusFilled: typeof import('~icons/ep/circle-plus-filled')['default'];
    IEpDeleteFilled: typeof import('~icons/ep/delete-filled')['default'];
    IEpEdit: typeof import('~icons/ep/edit')['default'];
    IEpExpand: typeof import('~icons/ep/expand')['default'];
    IEpFold: typeof import('~icons/ep/fold')['default'];
    IEpLock: typeof import('~icons/ep/lock')['default'];
    IEpRefresh: typeof import('~icons/ep/refresh')['default'];
    IEpUser: typeof import('~icons/ep/user')['default'];
    Pagination: typeof import('./src/components/QiTable/components/Pagination.vue')['default'];
    QiCard: typeof import('./src/components/QiCard/index.vue')['default'];
    QiDialog: typeof import('./src/components/QiDialog/index.vue')['default'];
    QiDictSelect: typeof import('./src/components/QiDictSelect/index.vue')['default'];
    QiEcharts: typeof import('./src/components/QiEcharts/index.vue')['default'];
    QiForm: typeof import('./src/components/QiForm/index.vue')['default'];
    QiLoading: typeof import('./src/components/QiLoading/index.vue')['default'];
    QiSearchForm: typeof import('./src/components/QiSearchForm/index.vue')['default'];
    QiSearchFormItem: typeof import('./src/components/QiSearchForm/components/QiSearchFormItem.vue')['default'];
    QiSliderVue2: typeof import('./src/components/QiSliderVue2/index.vue')['default'];
    QiTable: typeof import('./src/components/QiTable/index.vue')['default'];
    QiTsFormItem: typeof import('./src/components/QiForm/components/QiTsFormItem.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    TableColumn: typeof import('./src/components/QiTable/components/TableColumn.vue')['default'];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective'];
  }
}
